server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3309/Identity_Service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "ImAUSCYv3loAsgmM1oPUnYXSNsI75pspe7HE9DXkbTwgiq/03IyTkKP31+ZDEWMQ"